language: node_js
sudo: false
env:
- CXX=g++-4.8
node_js:
- "4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  global:
    - secure: boQGK3DJChwL9XlmsiPkSFnRiAzDNLFChnLlJDdByyaPdUJ+l6RBLs5CCk71zjLUX3bKA+H6z13y4y10LbXSSJMAgdoRZwj7ejqOnzYfIBiN2ownqCadeLusp7AJylYCZN5SpUpouG2ZEx0cTCtF0k2dQxS6+QHV7fc/t4VXRjg=
    - secure: Y6KjKj0HHMt/pYv7V8NUlHnxrVAc8luMWp0OC2AJBGeqP1IT8rDnOSqEmNyLWFLqpN4GbeKU1BW2BGDUfpg9qwhwMF+Qgfu/4A8TrLyEzMH2qS2WCvc9tbCPGzdDHpOe08PVlLW30Q8efso9g3DfHeh7StDgD14exLQ5DCX++Os=

script: ./travis.sh

addons:
  code_climate:
    repo_token: 8693ee93157c5b7c5232a9f74a43a8a836d8e0393d7218a779b569f20c28474c

after_success:
- npm run-script coveralls
- npm run-script codeclimate
